# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pigeonhole < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://pigeono.io/"
  version "0.1.12"

  on_macos do
    url "https://releases.pigeono.io/cli/0.1.12/pigeonhole_0.1.12_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "606e80f8fe77e717832b9715d2503afb8473341e4f856d3e1a2ca712b2c1ec17"

    def install
      bin.install "pigeonhole"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pigeonhole
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://releases.pigeono.io/cli/0.1.12/pigeonhole_0.1.12_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d5894215e0f9c87e5f9fce61296d7ec347a94230dbf981d23b3d34f4b77a3fd8"

      def install
        bin.install "pigeonhole"
      end
    end
  end
end
