# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pigeonhole < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://pigeono.io/"
  version "0.1.13"

  on_macos do
    url "https://releases.pigeono.io/cli/0.1.13/pigeonhole_0.1.13_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "c38d403fd47e0aaf73515396a8272a6ab9404228f888d574044eee98d7defa92"

    def install
      bin.install "pigeonhole"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pigeonhole
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://releases.pigeono.io/cli/0.1.13/pigeonhole_0.1.13_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d8f2f7750575aa143ebde167fa8c942af23d2f3bd111da00a9b5dbc98407d1b7"

      def install
        bin.install "pigeonhole"
      end
    end
  end
end
