# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pigeonhole < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://pigeono.io/"
  version "0.1.11"

  on_macos do
    url "https://releases.pigeono.io/cli/0.1.11/pigeonhole_0.1.11_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "e27c2bcd344a7e19ece09cd7eb8523f99e5aeefc87dc381a2dcca5b0492f76da"

    def install
      bin.install "pigeonhole"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pigeonhole
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://releases.pigeono.io/cli/0.1.11/pigeonhole_0.1.11_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d34bdef9a67f9ea7dbf744d4e09abb57327a1a7a642a94d2ada95635fa2e7826"

      def install
        bin.install "pigeonhole"
      end
    end
  end
end
